Repository YouQube/PlayVideo, pull requests merged in 2024-02, with the labels that each got.

#29 #28 Youtube api search endpoint 통신 기능 추가
  app/src/main/java/com/brandon/playvideo_app/data/api/NetworkClient.kt
  app/src/main/java/com/brandon/playvideo_app/data/api/RetrofitInstance.kt
  app/src/main/java/com/brandon/playvideo_app/data/api/YouTubeApi.kt
  app/src/main/java/com/brandon/playvideo_app/data/model/ErrorResponse.kt
  app/src/main/java/com/brandon/playvideo_app/data/model/RepositoryResult.kt
  app/src/main/java/com/brandon/playvideo_app/data/model/SubscribedChannelItem.kt
  app/src/main/java/com/brandon/playvideo_app/data/model/TrendVideoModel.kt
  app/src/main/java/com/brandon/playvideo_app/data/model/YoutubeSearchResponse.kt
  app/src/main/java/com/brandon/playvideo_app/data/repository/YoutubeSearchRepository.kt
  app/src/main/java/com/brandon/playvideo_app/data/repository/impl/YoutubeSearchRepositoryImpl.kt
  app/src/main/java/com/brandon/playvideo_app/ui/main/MainActivity.kt
  app/src/main/java/com/brandon/playvideo_app/ui/subscription/SubscriptionFragment.kt
  app/src/main/java/com/brandon/playvideo_app/ui/subscription/SubscriptionViewModel.kt
  app/src/main/java/com/brandon/playvideo_app/ui/subscription/SubscriptionViewModelFactory.kt
  app/src/main/java/com/brandon/playvideo_app/util/RetrofitUtil.kt
  app/src/main/java/com/brandon/playvideo_app/util/YoutubeSearchConverter.kt
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/values/themes.xml
Labels: documentation

#30 [Fix] VideoModel 충돌 문제 해결
  app/src/main/java/com/brandon/playvideo_app/data/model/SubscribedChannelItem.kt
  app/src/main/java/com/brandon/playvideo_app/util/YoutubeSearchConverter.kt
Labels: bug, enhancement

#31 TrendFragment/CategoryFramgnet MVVM 패턴 적용했습니다.
  app/build.gradle.kts
  app/src/main/java/com/brandon/playvideo_app/data/api/YouTubeApi.kt
  app/src/main/java/com/brandon/playvideo_app/repository/PlayVideoRepository.kt
  app/src/main/java/com/brandon/playvideo_app/ui/category/CategoryFragment.kt
  app/src/main/java/com/brandon/playvideo_app/ui/trend/TrendFragment.kt
  app/src/main/java/com/brandon/playvideo_app/ui/trend/VideoAdapter.kt
  app/src/main/java/com/brandon/playvideo_app/viewmodel/CategoryViewModel.kt
  app/src/main/java/com/brandon/playvideo_app/viewmodel/TrendViewModel.kt
  app/src/main/res/drawable/ic_scroll_to_top.png
  app/src/main/res/layout/category_fragment.xml
  app/src/main/res/layout/trend_fragment.xml
  settings.gradle.kts
Labels: enhancement

#40 Feat/subscription 영상 상세페이지 동영상 재생 기능 추가
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/java/com/brandon/playvideo_app/ui/detail/video/VideoDetailFragment.kt
  app/src/main/res/layout/detail_video_fragment.xml
Labels: enhancement
